<?php
// $Id: css_emimage.install,v 1.1 2010/03/01 23:07:49 jcarnett Exp $

/**
 * Implementation of hook_install().
 */
function css_emimage_install() {
  // Set the module's weight high so that it runs after other modules.
  db_query("UPDATE {system} SET weight = 9999 WHERE name = 'css_emimage' AND type = 'module'");
  cache_clear_all();
}

/**
 * Implementation of hook_uninstall().
 */
function css_emimage_uninstall() {
  variable_del('css_emimage_ielimit');
}
